### ISSUE TITLE
Failed to refreshStatus: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by mcackay** [yasuoza/homebridge-echonet-lite-heater-cooler#36]
Hi Yasuharu - 

I spotted this in the logs, and thought i'd let you know. The Aircon is still working fine as far as I can tell -- so let me know if you **don't** want non-impacting bug reports. But in case you're keen to 'run potential bugs to ground', I though i'd share.

```
[2/27/2022, 12:48:35 PM] [HeaterCooler] Failed to refreshStatus: Cannot read property 'message' of undefined
[2/27/2022, 1:46:35 PM] [HeaterCooler] Failed to refreshStatus: Cannot read property 'message' of undefined
```
As always, let me know if there's any more info you could benefit from to debug this.

--

Also, a quick Q. This plugin wasn't yet available in the Homebridge 'Plugins' install results ... so when a new version is available, will it show under the Plugins panel and prompt to update?  Or will i need to update it manually?

**Comment by yasuoza** [comment]
Sometime echonet lite device returns null responses.
Consulting to manufacturer may resolve the issue.
